### ISSUE TITLE
Need bs-platform as a dependency

### ISSUE THREAD

**Issue by Tmarty** [relekang/caretaker#2]
I recieve the error below immediately when running the caretaker command. I can look into it myself if you are accepting PR's :)
```
module.js:529
    throw err;
    ^

Error: Cannot find module 'bs-platform/lib/js/curry.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/tm/dev/programs/node-v8.6.0-linux-x64/lib/node_modules/@relekang/caretaker/src/main.js:5:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by relekang** [comment]
Oh, that is not good. Workaround can be to do `npm i -g bs-platform`. I don't know it bs-platform should be an dependency or if this should be fixed in another way.

**Comment by relekang** [comment]
I pushed a new version with bs-platform as a dependency, going to look into if there is a better way.

**Comment by Tmarty** [comment]
I can confirm it now works for me at least 👌

**Comment by relekang** [comment]
`@relekang/caretaker@0.3.0` contains a bundle instead of bs-platform as a dependency.
